import { useState } from 'react';
import { Link } from 'wouter';
import { Bell, Pause, Play, Radar, Trash2 } from 'lucide-react';
import { NetworkApiError, useAlertStatus, useAlertTriggers, useAlerts, useCreateAlert, useDeleteAlert, useRunAlert, useUpdateAlert } from '../hooks/use-network';

const initial = { title: '', keywords: '', skills: '', industries: '', minScore: 70, radiusKm: 25, trustRequirement: 'contact', frequency: 'instant' };
export default function Alerts() {
  const [form, setForm] = useState(initial);
  const [editingId, setEditingId] = useState<string>();
  const [selected, setSelected] = useState<string>();
  const alerts = useAlerts(); const create = useCreateAlert(); const update = useUpdateAlert(); const remove = useDeleteAlert(); const pause = useAlertStatus('pause'); const resume = useAlertStatus('resume'); const run = useRunAlert();
  const triggers = useAlertTriggers(selected);
  const submit = (event: React.FormEvent) => { event.preventDefault(); const input = { title: form.title, criteria: { keywords: split(form.keywords), skills: split(form.skills), industries: split(form.industries), wantCategories: [], offerCategories: [], minScore: form.minScore }, radiusKm: form.radiusKm, trustRequirement: form.trustRequirement, frequency: form.frequency }; const done = () => { setForm(initial); setEditingId(undefined); }; editingId ? update.mutate({ id: editingId, input }, { onSuccess: done }) : create.mutate(input, { onSuccess: done }); };
  const upgrade = create.error instanceof NetworkApiError && create.error.status === 402;
  return <div className="p-6 md:p-10 max-w-6xl mx-auto"><header className="mb-8"><p className="text-xs font-mono-custom uppercase tracking-widest text-primary font-semibold">Standing XSECTs</p><h1 className="text-3xl md:text-4xl font-bold mt-3">Keep Radar watching</h1><p className="text-sm text-muted-foreground mt-2">Define a signal once. XSECT evaluates it against your real opportunity graph.</p></header>
    <div className="grid lg:grid-cols-[0.8fr_1.2fr] gap-6 items-start"><form onSubmit={submit} className="bg-white border rounded-2xl p-5 grid gap-4 shadow-sm"><h2 className="font-bold">Create Standing XSECT</h2><input required minLength={2} className="border rounded-lg p-2.5 text-sm" placeholder="Alert title" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /><input className="border rounded-lg p-2.5 text-sm" placeholder="Keywords, comma separated" value={form.keywords} onChange={(e) => setForm({ ...form, keywords: e.target.value })} /><input className="border rounded-lg p-2.5 text-sm" placeholder="Skills" value={form.skills} onChange={(e) => setForm({ ...form, skills: e.target.value })} /><input className="border rounded-lg p-2.5 text-sm" placeholder="Industries" value={form.industries} onChange={(e) => setForm({ ...form, industries: e.target.value })} /><label className="text-xs text-muted-foreground">Minimum XSECT Score: {form.minScore}<input className="w-full mt-2" type="range" min={0} max={100} value={form.minScore} onChange={(e) => setForm({ ...form, minScore: Number(e.target.value) })} /></label><div className="grid grid-cols-2 gap-3"><input className="border rounded-lg p-2 text-sm" type="number" min={1} max={500} value={form.radiusKm} onChange={(e) => setForm({ ...form, radiusKm: Number(e.target.value) })} /><select className="border rounded-lg p-2 text-sm" value={form.frequency} onChange={(e) => setForm({ ...form, frequency: e.target.value })}><option value="instant">Instant</option><option value="daily">Daily</option><option value="weekly">Weekly</option></select></div><button className="rounded-lg bg-foreground text-background py-3 text-sm font-bold" disabled={create.isPending}>{create.isPending ? 'Creating…' : 'Create Standing XSECT'}</button>{upgrade && <div className="rounded-lg bg-primary/5 p-3 text-sm">Standing XSECTs require Pro. <Link href="/plans" className="text-primary font-bold">View plans</Link></div>}{create.isError && !upgrade && <p className="text-xs text-destructive">{create.error.message}</p>}</form>
      <section className="space-y-4">{alerts.isLoading && <p className="text-sm text-muted-foreground">Loading Standing XSECTs…</p>}{alerts.data?.alerts.map((alert) => <article key={alert.id} className={`bg-white border rounded-2xl p-5 shadow-sm ${selected === alert.id ? 'border-primary' : ''}`}><button className="text-left w-full" onClick={() => setSelected(alert.id)}><div className="flex justify-between gap-3"><div><h3 className="font-bold flex items-center gap-2"><Bell size={15} />{alert.title}</h3><p className="text-xs text-muted-foreground mt-1">{alert.criteria.keywords.concat(alert.criteria.skills, alert.criteria.industries).join(' · ') || `All active XSECTs over ${alert.criteria.minScore}`}</p></div><span className="text-xs font-mono-custom uppercase">{alert.status}</span></div><p className="text-xs mt-3">{alert.triggerCount} triggers · {alert.frequency} · {alert.radiusKm}km configured radius</p></button><div className="flex gap-2 mt-4"><button onClick={() => run.mutate(alert.id)} className="text-xs font-bold px-3 py-2 rounded-lg bg-primary text-primary-foreground flex gap-1"><Radar size={13} /> Run now</button><button onClick={() => { setEditingId(alert.id); setForm({ title: alert.title, keywords: alert.criteria.keywords.join(', '), skills: alert.criteria.skills.join(', '), industries: alert.criteria.industries.join(', '), minScore: alert.criteria.minScore, radiusKm: alert.radiusKm, trustRequirement: alert.trustRequirement, frequency: alert.frequency }); }} className="text-xs px-3 py-2">Edit</button>{alert.status === 'active' ? <button onClick={() => pause.mutate(alert.id)} className="text-xs px-3 py-2 flex gap-1"><Pause size={13} />Pause</button> : <button onClick={() => resume.mutate(alert.id)} className="text-xs px-3 py-2 flex gap-1"><Play size={13} />Resume</button>}<button onClick={() => remove.mutate(alert.id)} className="ml-auto text-destructive"><Trash2 size={15} /></button></div></article>)}{alerts.data?.alerts.length === 0 && <div className="border border-dashed rounded-2xl p-10 text-center"><Bell className="mx-auto text-muted-foreground" /><p className="font-bold mt-3">No Standing XSECTs yet</p></div>}</section></div>
    {selected && <section className="mt-8"><h2 className="font-bold text-lg border-b pb-3">Triggers</h2><div className="grid md:grid-cols-2 gap-4 mt-4">{triggers.data?.triggers.map((trigger) => <div key={trigger.id} className="bg-white border rounded-xl p-4"><div className="flex justify-between"><p className="font-bold">{trigger.counterpart.revealed ? trigger.counterpart.displayName : trigger.counterpart.handle}</p><span className="font-bold text-primary">{trigger.score}</span></div><p className="text-xs text-muted-foreground">{trigger.counterpart.role} · {trigger.counterpart.trustLevel} trust</p><p className="text-sm mt-3">{trigger.explanation[0]}</p></div>)}</div>{triggers.data?.triggers.length === 0 && <p className="text-sm text-muted-foreground py-6">No XSECTs have triggered this alert.</p>}</section>}
  </div>;
}
const split = (value: string) => value.split(',').map((item) => item.trim()).filter(Boolean);
