import { useState } from 'react';
import { Pencil, ShieldCheck, Trash2, UserPlus } from 'lucide-react';
import { useParams } from 'wouter';
import { useOrganization, useOrganizationActions } from '../hooks/use-organizations';
import { useToast } from '@/hooks/use-toast';

const opportunityBlank = { type: 'job', title: '', description: '', skills: '', industry: '', workMode: 'flexible', city: '', area: '', intent: 'active', expiresAt: '' };
export default function OrganizationDetail() {
  const { id } = useParams<{ id: string }>(); const query = useOrganization(id); const actions = useOrganizationActions(id); const { toast } = useToast();
  const [memberId, setMemberId] = useState(''); const [memberRole, setMemberRole] = useState<'member' | 'admin'>('member'); const [form, setForm] = useState(opportunityBlank);
  if (query.isLoading) return <div className="p-10 text-muted-foreground">Loading organization…</div>;
  if (query.isError || !query.data) return <div className="p-10 text-destructive">Organization not found.</div>;
  const { organization, members, opportunities, viewerRole } = query.data; const admin = viewerRole === 'owner' || viewerRole === 'admin';
  const run = async (action: () => Promise<unknown>, message: string) => { try { await action(); toast({ title: message }); } catch (error) { toast({ title: 'Action failed', description: error instanceof Error ? error.message : 'Try again.', variant: 'destructive' }); } };
  return <div className="p-6 md:p-10 max-w-6xl mx-auto"><header className="bg-white border rounded-2xl p-7 mb-8"><div className="flex justify-between gap-5"><div><p className="text-xs uppercase tracking-widest font-mono-custom text-primary">{organization.verificationState === 'verified' ? 'Confirmed organization' : 'Organization profile'}</p><h1 className="text-4xl font-bold mt-2">{organization.name}</h1><p className="text-sm text-muted-foreground mt-2">{[organization.industry, organization.size, organization.city, organization.area].filter(Boolean).join(' · ')}</p></div><div className="flex items-start gap-3">{admin && <button onClick={() => { const description = prompt('Organization description', organization.description); if (description !== null) void run(() => actions.update.mutateAsync({ description }), 'Organization updated'); }} className="border rounded-lg px-3 py-2 text-sm font-bold flex gap-2"><Pencil size={15} />Edit</button>}{organization.logoUrl && <img src={organization.logoUrl} alt="" className="w-20 h-20 object-contain rounded-xl border" />}</div></div><p className="mt-5 text-muted-foreground">{organization.description || 'No description provided.'}</p>{organization.website && <a href={organization.website} target="_blank" rel="noreferrer" className="text-primary text-sm mt-3 inline-block">Visit website</a>}</header>
    <div className="grid lg:grid-cols-[1fr_1.5fr] gap-8"><section><h2 className="text-xl font-bold mb-4">Members</h2><div className="space-y-3">{members.map((member) => <div key={member.id} className="bg-white border rounded-xl p-4 flex justify-between items-center"><div className="flex gap-3 items-center"><ShieldCheck size={18} className="text-primary" /><div><p className="font-bold">{member.displayName ?? member.role ?? 'Protected member'}</p><p className="text-xs text-muted-foreground">{member.displayName ? member.role : 'Identity protected'} · {member.organizationRole}</p></div></div>{admin && member.organizationRole !== 'owner' && <button onClick={() => run(() => actions.removeMember.mutateAsync(member.id), 'Member removed')} className="text-destructive"><Trash2 size={16} /></button>}</div>)}</div>
      {admin && <div className="bg-white border rounded-xl p-4 mt-4"><h3 className="font-bold flex gap-2"><UserPlus size={17} />Add member</h3><input value={memberId} onChange={(e) => setMemberId(e.target.value)} placeholder="Clerk user ID" className="mt-3 w-full border rounded-lg px-3 py-2 text-sm" /><select value={memberRole} onChange={(e) => setMemberRole(e.target.value as 'member' | 'admin')} className="mt-2 w-full border rounded-lg px-3 py-2 text-sm"><option value="member">Member</option><option value="admin">Admin</option></select><button onClick={() => run(() => actions.addMember.mutateAsync({ userId: memberId, role: memberRole }), 'Member added')} className="mt-3 w-full bg-foreground text-background rounded-lg py-2 text-sm font-bold">Add member</button></div>}</section>
      <section><h2 className="text-xl font-bold mb-4">Active opportunities</h2>{opportunities.length ? <div className="space-y-3">{opportunities.map((opportunity) => <article key={opportunity.id} className="bg-white border rounded-xl p-5"><div className="flex justify-between"><span className="text-xs bg-primary/10 text-primary rounded-full px-2 py-1">{opportunity.type}</span>{admin && <div className="flex gap-3"><button onClick={() => { const title = prompt('Opportunity title', opportunity.title); if (title) void run(() => actions.updateOpportunity.mutateAsync({ opportunityId: opportunity.id, input: { title } }), 'Opportunity updated'); }}><Pencil size={16} /></button><button onClick={() => run(() => actions.removeOpportunity.mutateAsync(opportunity.id), 'Opportunity deleted')} className="text-destructive"><Trash2 size={16} /></button></div>}</div><h3 className="font-bold text-lg mt-3">{opportunity.title}</h3><p className="text-sm text-muted-foreground mt-2">{opportunity.description}</p><p className="text-xs text-muted-foreground mt-3">{[opportunity.workMode.replace('_', ' '), opportunity.city, opportunity.industry].filter(Boolean).join(' · ')}</p></article>)}</div> : <div className="p-8 border border-dashed rounded-xl text-center text-muted-foreground">No active opportunities.</div>}
        {admin && <div className="bg-white border rounded-xl p-5 mt-5"><h3 className="font-bold">Post an opportunity</h3><div className="grid md:grid-cols-2 gap-3 mt-3">{(['title', 'industry', 'city', 'area'] as const).map((key) => <input key={key} placeholder={key} value={form[key]} onChange={(e) => setForm((old) => ({ ...old, [key]: e.target.value }))} className="border rounded-lg px-3 py-2 text-sm" />)}<select value={form.type} onChange={(e) => setForm((old) => ({ ...old, type: e.target.value }))} className="border rounded-lg px-3 py-2 text-sm">{['job', 'partnership', 'freelance', 'vendor', 'mentorship', 'event', 'investor', 'collaboration', 'service'].map((type) => <option key={type}>{type}</option>)}</select><select value={form.workMode} onChange={(e) => setForm((old) => ({ ...old, workMode: e.target.value }))} className="border rounded-lg px-3 py-2 text-sm">{['flexible', 'remote', 'hybrid', 'in_person'].map((mode) => <option key={mode}>{mode}</option>)}</select><input placeholder="Skills, comma-separated" value={form.skills} onChange={(e) => setForm((old) => ({ ...old, skills: e.target.value }))} className="md:col-span-2 border rounded-lg px-3 py-2 text-sm" /><textarea placeholder="Description" value={form.description} onChange={(e) => setForm((old) => ({ ...old, description: e.target.value }))} className="md:col-span-2 border rounded-lg px-3 py-2 text-sm" rows={3} /><input type="date" value={form.expiresAt} onChange={(e) => setForm((old) => ({ ...old, expiresAt: e.target.value }))} className="border rounded-lg px-3 py-2 text-sm" /></div><button onClick={() => run(async () => { await actions.createOpportunity.mutateAsync({ ...form, skills: form.skills.split(',').map((x) => x.trim()).filter(Boolean), expiresAt: form.expiresAt ? new Date(form.expiresAt).toISOString() : null }); setForm(opportunityBlank); }, 'Opportunity posted')} className="mt-4 w-full bg-primary text-primary-foreground rounded-lg py-2.5 font-bold">Post opportunity</button></div>}
      </section></div>
  </div>;
}