import { useState } from 'react';
import { Building2, Plus, Search, Sparkles, X } from 'lucide-react';
import { Link } from 'wouter';
import { useOrganizationActions, useOrganizationOpportunities, useOrganizations, useMyOrganizations, type OrganizationInput } from '../hooks/use-organizations';
import { useToast } from '@/hooks/use-toast';

const empty: OrganizationInput = { name: '', description: '', industry: null, size: null, city: null, area: null, website: null, logoUrl: null };
export default function Organizations() {
  const [tab, setTab] = useState<'directory' | 'mine' | 'opportunities'>('directory'); const [q, setQ] = useState(''); const [createOpen, setCreateOpen] = useState(false);
  const [form, setForm] = useState(empty); const directory = useOrganizations({ q }); const mine = useMyOrganizations(); const opportunities = useOrganizationOpportunities(); const actions = useOrganizationActions(); const { toast } = useToast();
  const create = async () => { try { await actions.create.mutateAsync(form); setCreateOpen(false); setForm(empty); toast({ title: 'Organization created', description: 'You are now its owner.' }); } catch (error) { toast({ title: 'Unable to create', description: error instanceof Error ? error.message : 'Try again.', variant: 'destructive' }); } };
  return <div className="p-6 md:p-10 max-w-6xl mx-auto"><header className="flex flex-col md:flex-row md:items-end justify-between gap-5 mb-8"><div><p className="text-xs font-mono-custom uppercase tracking-widest text-primary font-semibold mb-3">Organization network</p><h1 className="text-4xl font-bold">Organizations</h1><p className="text-sm text-muted-foreground mt-2">Explore real organizations and opportunities crossing your path.</p></div><button onClick={() => setCreateOpen(true)} className="bg-foreground text-background px-4 py-2.5 rounded-lg font-bold text-sm flex gap-2"><Plus size={17} />Create organization</button></header>
    <div className="flex gap-2 border-b mb-6">{([['directory', 'Directory'], ['mine', 'My organizations'], ['opportunities', 'Opportunities']] as const).map(([value, label]) => <button key={value} onClick={() => setTab(value)} className={`px-4 py-3 text-sm font-bold border-b-2 ${tab === value ? 'border-primary text-primary' : 'border-transparent text-muted-foreground'}`}>{label}</button>)}</div>
    {tab === 'directory' && <><div className="relative mb-6 max-w-md"><Search size={17} className="absolute left-3 top-3 text-muted-foreground" /><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search name or description" className="w-full pl-10 pr-3 py-2.5 bg-white border rounded-lg" /></div><OrgGrid organizations={directory.data?.organizations ?? []} loading={directory.isLoading} /></>}
    {tab === 'mine' && <OrgGrid organizations={(mine.data?.organizations ?? []).map((item) => item.organization)} loading={mine.isLoading} empty="You have not joined an organization yet." />}
    {tab === 'opportunities' && <div className="grid md:grid-cols-2 gap-4">{opportunities.isLoading ? <p>Loading…</p> : opportunities.data?.opportunities.length ? opportunities.data.opportunities.map(({ opportunity, organization, fit }) => <article key={opportunity.id} className="bg-white border rounded-xl p-5"><div className="flex justify-between gap-3"><span className="text-xs bg-secondary rounded-full px-2 py-1">{opportunity.type}</span><span className="font-mono-custom text-xs font-bold text-primary flex gap-1"><Sparkles size={14} />{fit.score}% fit</span></div><h3 className="font-bold text-lg mt-3">{opportunity.title}</h3><Link href={`/organizations/${organization.id}`} className="text-sm text-primary">{organization.name}</Link><p className="text-sm text-muted-foreground mt-2">{opportunity.description}</p><ul className="text-xs text-muted-foreground mt-3 space-y-1">{fit.explanation.map((line) => <li key={line}>• {line}</li>)}</ul></article>) : <p className="text-muted-foreground">No active organization opportunities are available.</p>}</div>}
    {createOpen && <div className="fixed inset-0 z-50 bg-black/40 grid place-items-center p-4"><div className="bg-white rounded-2xl p-6 w-full max-w-lg max-h-[90vh] overflow-auto"><div className="flex justify-between"><h2 className="text-xl font-bold">Create organization</h2><button onClick={() => setCreateOpen(false)}><X /></button></div><div className="space-y-3 mt-5">{(['name', 'industry', 'size', 'city', 'area', 'website', 'logoUrl'] as const).map((key) => <label key={key} className="block text-sm font-medium capitalize">{key.replace('Url', ' URL')}<input value={form[key] ?? ''} onChange={(e) => setForm((old) => ({ ...old, [key]: e.target.value || null }))} className="mt-1 w-full border rounded-lg px-3 py-2" /></label>)}<label className="block text-sm font-medium">Description<textarea value={form.description} onChange={(e) => setForm((old) => ({ ...old, description: e.target.value }))} className="mt-1 w-full border rounded-lg px-3 py-2" rows={4} /></label></div><button onClick={create} disabled={actions.create.isPending} className="mt-5 w-full bg-primary text-primary-foreground rounded-lg py-2.5 font-bold">Create</button></div></div>}
  </div>;
}
function OrgGrid({ organizations, loading, empty = 'No organizations found.' }: { organizations: Array<{ id: string; name: string; description: string; industry: string | null; city: string | null }>; loading: boolean; empty?: string }) {
  if (loading) return <p className="text-muted-foreground">Loading…</p>;
  if (!organizations.length) return <div className="p-10 border border-dashed rounded-xl text-center text-muted-foreground">{empty}</div>;
  return <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{organizations.map((organization) => <Link key={organization.id} href={`/organizations/${organization.id}`} className="bg-white border rounded-xl p-5 hover:border-primary transition-colors"><Building2 className="text-primary mb-4" /><h3 className="font-bold text-lg">{organization.name}</h3><p className="text-xs text-muted-foreground mt-1">{[organization.industry, organization.city].filter(Boolean).join(' · ') || 'Organization profile'}</p><p className="text-sm text-muted-foreground mt-3 line-clamp-3">{organization.description || 'No description provided.'}</p></Link>)}</div>;
}